// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: kitchen.proto

package kitchenproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DishItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DishId string `protobuf:"bytes,1,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	Dish   string `protobuf:"bytes,2,opt,name=dish,proto3" json:"dish,omitempty"`
	Total  int32  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *DishItem) Reset() {
	*x = DishItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DishItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishItem) ProtoMessage() {}

func (x *DishItem) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishItem.ProtoReflect.Descriptor instead.
func (*DishItem) Descriptor() ([]byte, []int) {
	return file_kitchen_proto_rawDescGZIP(), []int{0}
}

func (x *DishItem) GetDishId() string {
	if x != nil {
		return x.DishId
	}
	return ""
}

func (x *DishItem) GetDish() string {
	if x != nil {
		return x.Dish
	}
	return ""
}

func (x *DishItem) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type VerifyOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreId string      `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Dishes  []*DishItem `protobuf:"bytes,2,rep,name=dishes,proto3" json:"dishes,omitempty"`
}

func (x *VerifyOrderRequest) Reset() {
	*x = VerifyOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOrderRequest) ProtoMessage() {}

func (x *VerifyOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOrderRequest.ProtoReflect.Descriptor instead.
func (*VerifyOrderRequest) Descriptor() ([]byte, []int) {
	return file_kitchen_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyOrderRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *VerifyOrderRequest) GetDishes() []*DishItem {
	if x != nil {
		return x.Dishes
	}
	return nil
}

type VerifyOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOk bool `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
}

func (x *VerifyOrderResponse) Reset() {
	*x = VerifyOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOrderResponse) ProtoMessage() {}

func (x *VerifyOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOrderResponse.ProtoReflect.Descriptor instead.
func (*VerifyOrderResponse) Descriptor() ([]byte, []int) {
	return file_kitchen_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyOrderResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

type CreatePendingTicketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	OrderId   string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *CreatePendingTicketRequest) Reset() {
	*x = CreatePendingTicketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePendingTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePendingTicketRequest) ProtoMessage() {}

func (x *CreatePendingTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePendingTicketRequest.ProtoReflect.Descriptor instead.
func (*CreatePendingTicketRequest) Descriptor() ([]byte, []int) {
	return file_kitchen_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePendingTicketRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreatePendingTicketRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CreatePendingTicketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOk bool `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
}

func (x *CreatePendingTicketResponse) Reset() {
	*x = CreatePendingTicketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePendingTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePendingTicketResponse) ProtoMessage() {}

func (x *CreatePendingTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePendingTicketResponse.ProtoReflect.Descriptor instead.
func (*CreatePendingTicketResponse) Descriptor() ([]byte, []int) {
	return file_kitchen_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePendingTicketResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

type CancelTicketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TicketId string `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
}

func (x *CancelTicketRequest) Reset() {
	*x = CancelTicketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTicketRequest) ProtoMessage() {}

func (x *CancelTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTicketRequest.ProtoReflect.Descriptor instead.
func (*CancelTicketRequest) Descriptor() ([]byte, []int) {
	return file_kitchen_proto_rawDescGZIP(), []int{5}
}

func (x *CancelTicketRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

type CancelTicketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOk bool `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
}

func (x *CancelTicketResponse) Reset() {
	*x = CancelTicketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTicketResponse) ProtoMessage() {}

func (x *CancelTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTicketResponse.ProtoReflect.Descriptor instead.
func (*CancelTicketResponse) Descriptor() ([]byte, []int) {
	return file_kitchen_proto_rawDescGZIP(), []int{6}
}

func (x *CancelTicketResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

type AcceptTicketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TicketId string `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
}

func (x *AcceptTicketRequest) Reset() {
	*x = AcceptTicketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptTicketRequest) ProtoMessage() {}

func (x *AcceptTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptTicketRequest.ProtoReflect.Descriptor instead.
func (*AcceptTicketRequest) Descriptor() ([]byte, []int) {
	return file_kitchen_proto_rawDescGZIP(), []int{7}
}

func (x *AcceptTicketRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

type AcceptTicketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOk bool `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
}

func (x *AcceptTicketResponse) Reset() {
	*x = AcceptTicketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptTicketResponse) ProtoMessage() {}

func (x *AcceptTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptTicketResponse.ProtoReflect.Descriptor instead.
func (*AcceptTicketResponse) Descriptor() ([]byte, []int) {
	return file_kitchen_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptTicketResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

var File_kitchen_proto protoreflect.FileDescriptor

var file_kitchen_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x22, 0x4d, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x68,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x69, 0x73, 0x68, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x69, 0x73, 0x68, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x69, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x69, 0x73,
	0x68, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x5a, 0x0a, 0x12, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x06, 0x64, 0x69, 0x73, 0x68,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6b, 0x69, 0x74, 0x63, 0x68,
	0x65, 0x6e, 0x2e, 0x44, 0x69, 0x73, 0x68, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x64, 0x69, 0x73,
	0x68, 0x65, 0x73, 0x22, 0x2a, 0x0a, 0x13, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73,
	0x5f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x22,
	0x56, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f, 0x6f, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x22, 0x32, 0x0a, 0x13, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x22,
	0x2b, 0x0a, 0x14, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f, 0x6f, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x22, 0x32, 0x0a, 0x13,
	0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64,
	0x22, 0x2b, 0x0a, 0x14, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x32, 0xd6, 0x02,
	0x0a, 0x0e, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x48, 0x0a, 0x0b, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x1b, 0x2e, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6b,
	0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x23, 0x2e, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0c,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1c, 0x2e, 0x6b,
	0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6b, 0x69, 0x74,
	0x63, 0x68, 0x65, 0x6e, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x41, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1c, 0x2e, 0x6b, 0x69, 0x74, 0x63,
	0x68, 0x65, 0x6e, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65,
	0x6e, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x74, 0x63, 0x2d, 0x67, 0x6f, 0x65, 0x72, 0x2f, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x2f, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x3b, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kitchen_proto_rawDescOnce sync.Once
	file_kitchen_proto_rawDescData = file_kitchen_proto_rawDesc
)

func file_kitchen_proto_rawDescGZIP() []byte {
	file_kitchen_proto_rawDescOnce.Do(func() {
		file_kitchen_proto_rawDescData = protoimpl.X.CompressGZIP(file_kitchen_proto_rawDescData)
	})
	return file_kitchen_proto_rawDescData
}

var file_kitchen_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_kitchen_proto_goTypes = []any{
	(*DishItem)(nil),                    // 0: kitchen.DishItem
	(*VerifyOrderRequest)(nil),          // 1: kitchen.VerifyOrderRequest
	(*VerifyOrderResponse)(nil),         // 2: kitchen.VerifyOrderResponse
	(*CreatePendingTicketRequest)(nil),  // 3: kitchen.CreatePendingTicketRequest
	(*CreatePendingTicketResponse)(nil), // 4: kitchen.CreatePendingTicketResponse
	(*CancelTicketRequest)(nil),         // 5: kitchen.CancelTicketRequest
	(*CancelTicketResponse)(nil),        // 6: kitchen.CancelTicketResponse
	(*AcceptTicketRequest)(nil),         // 7: kitchen.AcceptTicketRequest
	(*AcceptTicketResponse)(nil),        // 8: kitchen.AcceptTicketResponse
}
var file_kitchen_proto_depIdxs = []int32{
	0, // 0: kitchen.VerifyOrderRequest.dishes:type_name -> kitchen.DishItem
	1, // 1: kitchen.KitchenService.VerifyOrder:input_type -> kitchen.VerifyOrderRequest
	3, // 2: kitchen.KitchenService.CreatePendingTicket:input_type -> kitchen.CreatePendingTicketRequest
	5, // 3: kitchen.KitchenService.CancelTicket:input_type -> kitchen.CancelTicketRequest
	7, // 4: kitchen.KitchenService.AcceptTicket:input_type -> kitchen.AcceptTicketRequest
	2, // 5: kitchen.KitchenService.VerifyOrder:output_type -> kitchen.VerifyOrderResponse
	4, // 6: kitchen.KitchenService.CreatePendingTicket:output_type -> kitchen.CreatePendingTicketResponse
	6, // 7: kitchen.KitchenService.CancelTicket:output_type -> kitchen.CancelTicketResponse
	8, // 8: kitchen.KitchenService.AcceptTicket:output_type -> kitchen.AcceptTicketResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kitchen_proto_init() }
func file_kitchen_proto_init() {
	if File_kitchen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kitchen_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DishItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchen_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchen_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchen_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreatePendingTicketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchen_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CreatePendingTicketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchen_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CancelTicketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchen_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*CancelTicketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchen_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*AcceptTicketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchen_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*AcceptTicketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kitchen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kitchen_proto_goTypes,
		DependencyIndexes: file_kitchen_proto_depIdxs,
		MessageInfos:      file_kitchen_proto_msgTypes,
	}.Build()
	File_kitchen_proto = out.File
	file_kitchen_proto_rawDesc = nil
	file_kitchen_proto_goTypes = nil
	file_kitchen_proto_depIdxs = nil
}
