# Can't use for testing localhost
version: "2"
services:
  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"
  fabio:
    image: fabiolb/fabio
    depends_on:
      - consul
    volumes:
      - ./fabio.properties:/etc/fabio/fabio.properties
    links:
      - consul
    ports:
      - "9999:9999"
      - "9998:9998"
    environment:
      - FABIO_OPTS=-cfg /etc/fabio/fabio.properties
