version: "3.9"
name: microservice-examples
services:
  # Can't be used to test services running on localhost
#  consul:
#    container_name: consul
#    image: consul:1.15.4
#    ports:
#      - "8500:8500"
#    volumes:
#      - ./consul_data/:/consul/data
#  fabio:
#    container_name: fabio
#    image: fabiolb/fabio
#    depends_on:
#      - consul
#    volumes:
#      - ./fabio.properties:/etc/fabio/fabio.properties
#    links:
#      - consul
#    ports:
#      - "9999:9999"
#      - "9998:9998"
#    environment:
#      - FABIO_OPTS=-cfg /etc/fabio/fabio.properties
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: UGP82fkcWU
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./init_user.sql:/docker-entrypoint-initdb.d/init_user.sql
    ports:
      - "5433:5432"
    networks:
      - postgres
#  pgAdmin web-based
  db_admin:
    container_name: db_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: 0SwSy1QIV7
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  nats:
    container_name: message_queue
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.22
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "9411:9411"
      - "14250:14250"
      - "16686:16686"
      - "14268:14268"
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:

