version: "3.9"
name: microservice-examples
services:
  # Can't be used to test services running on localhost
  consul:
    container_name: consul
    image: consul:1.15.4
    ports:
      - "8500:8500"
  fabio:
    container_name: fabio
    image: fabiolb/fabio
    depends_on:
      - consul
    volumes:
      - ./fabio.properties:/etc/fabio/fabio.properties
    links:
      - consul
    ports:
      - "9999:9999"
      - "9998:9998"
    environment:
      - FABIO_OPTS=-cfg /etc/fabio/fabio.properties
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: UGP82fkcWU
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped
#  pgAdmin web-based
  db_admin:
    container_name: db_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: 0SwSy1QIV7
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:

