// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/ntc-goer/microservice-examples/orderservice/ent/dish"
)

// DishCreate is the builder for creating a Dish entity.
type DishCreate struct {
	config
	mutation *DishMutation
	hooks    []Hook
}

// SetOrderID sets the "order_id" field.
func (dc *DishCreate) SetOrderID(u uuid.UUID) *DishCreate {
	dc.mutation.SetOrderID(u)
	return dc
}

// SetDishName sets the "dish_name" field.
func (dc *DishCreate) SetDishName(s string) *DishCreate {
	dc.mutation.SetDishName(s)
	return dc
}

// SetQuantity sets the "quantity" field.
func (dc *DishCreate) SetQuantity(i int) *DishCreate {
	dc.mutation.SetQuantity(i)
	return dc
}

// SetUpdateAt sets the "update_at" field.
func (dc *DishCreate) SetUpdateAt(t time.Time) *DishCreate {
	dc.mutation.SetUpdateAt(t)
	return dc
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (dc *DishCreate) SetNillableUpdateAt(t *time.Time) *DishCreate {
	if t != nil {
		dc.SetUpdateAt(*t)
	}
	return dc
}

// SetCreatedAt sets the "created_at" field.
func (dc *DishCreate) SetCreatedAt(t time.Time) *DishCreate {
	dc.mutation.SetCreatedAt(t)
	return dc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (dc *DishCreate) SetNillableCreatedAt(t *time.Time) *DishCreate {
	if t != nil {
		dc.SetCreatedAt(*t)
	}
	return dc
}

// SetID sets the "id" field.
func (dc *DishCreate) SetID(u uuid.UUID) *DishCreate {
	dc.mutation.SetID(u)
	return dc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (dc *DishCreate) SetNillableID(u *uuid.UUID) *DishCreate {
	if u != nil {
		dc.SetID(*u)
	}
	return dc
}

// Mutation returns the DishMutation object of the builder.
func (dc *DishCreate) Mutation() *DishMutation {
	return dc.mutation
}

// Save creates the Dish in the database.
func (dc *DishCreate) Save(ctx context.Context) (*Dish, error) {
	dc.defaults()
	return withHooks(ctx, dc.sqlSave, dc.mutation, dc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DishCreate) SaveX(ctx context.Context) *Dish {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dc *DishCreate) Exec(ctx context.Context) error {
	_, err := dc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dc *DishCreate) ExecX(ctx context.Context) {
	if err := dc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dc *DishCreate) defaults() {
	if _, ok := dc.mutation.UpdateAt(); !ok {
		v := dish.DefaultUpdateAt()
		dc.mutation.SetUpdateAt(v)
	}
	if _, ok := dc.mutation.CreatedAt(); !ok {
		v := dish.DefaultCreatedAt()
		dc.mutation.SetCreatedAt(v)
	}
	if _, ok := dc.mutation.ID(); !ok {
		v := dish.DefaultID()
		dc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dc *DishCreate) check() error {
	if _, ok := dc.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "Dish.order_id"`)}
	}
	if _, ok := dc.mutation.DishName(); !ok {
		return &ValidationError{Name: "dish_name", err: errors.New(`ent: missing required field "Dish.dish_name"`)}
	}
	if v, ok := dc.mutation.DishName(); ok {
		if err := dish.DishNameValidator(v); err != nil {
			return &ValidationError{Name: "dish_name", err: fmt.Errorf(`ent: validator failed for field "Dish.dish_name": %w`, err)}
		}
	}
	if _, ok := dc.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "Dish.quantity"`)}
	}
	if v, ok := dc.mutation.Quantity(); ok {
		if err := dish.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "Dish.quantity": %w`, err)}
		}
	}
	if _, ok := dc.mutation.UpdateAt(); !ok {
		return &ValidationError{Name: "update_at", err: errors.New(`ent: missing required field "Dish.update_at"`)}
	}
	if _, ok := dc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Dish.created_at"`)}
	}
	return nil
}

func (dc *DishCreate) sqlSave(ctx context.Context) (*Dish, error) {
	if err := dc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	dc.mutation.id = &_node.ID
	dc.mutation.done = true
	return _node, nil
}

func (dc *DishCreate) createSpec() (*Dish, *sqlgraph.CreateSpec) {
	var (
		_node = &Dish{config: dc.config}
		_spec = sqlgraph.NewCreateSpec(dish.Table, sqlgraph.NewFieldSpec(dish.FieldID, field.TypeUUID))
	)
	if id, ok := dc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := dc.mutation.OrderID(); ok {
		_spec.SetField(dish.FieldOrderID, field.TypeUUID, value)
		_node.OrderID = value
	}
	if value, ok := dc.mutation.DishName(); ok {
		_spec.SetField(dish.FieldDishName, field.TypeString, value)
		_node.DishName = value
	}
	if value, ok := dc.mutation.Quantity(); ok {
		_spec.SetField(dish.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if value, ok := dc.mutation.UpdateAt(); ok {
		_spec.SetField(dish.FieldUpdateAt, field.TypeTime, value)
		_node.UpdateAt = value
	}
	if value, ok := dc.mutation.CreatedAt(); ok {
		_spec.SetField(dish.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// DishCreateBulk is the builder for creating many Dish entities in bulk.
type DishCreateBulk struct {
	config
	err      error
	builders []*DishCreate
}

// Save creates the Dish entities in the database.
func (dcb *DishCreateBulk) Save(ctx context.Context) ([]*Dish, error) {
	if dcb.err != nil {
		return nil, dcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dcb.builders))
	nodes := make([]*Dish, len(dcb.builders))
	mutators := make([]Mutator, len(dcb.builders))
	for i := range dcb.builders {
		func(i int, root context.Context) {
			builder := dcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DishMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcb *DishCreateBulk) SaveX(ctx context.Context) []*Dish {
	v, err := dcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcb *DishCreateBulk) Exec(ctx context.Context) error {
	_, err := dcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcb *DishCreateBulk) ExecX(ctx context.Context) {
	if err := dcb.Exec(ctx); err != nil {
		panic(err)
	}
}
