// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ntc-goer/microservice-examples/registry/sagaorchestation/ent/predicate"
	"github.com/ntc-goer/microservice-examples/registry/sagaorchestation/ent/sagalogs"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeSagaLogs = "SagaLogs"
)

// SagaLogsMutation represents an operation that mutates the SagaLogs nodes in the graph.
type SagaLogsMutation struct {
	config
	op            Op
	typ           string
	id            *int
	workflow_id   *string
	workflow_name *string
	step_name     *string
	update_at     *time.Time
	created_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*SagaLogs, error)
	predicates    []predicate.SagaLogs
}

var _ ent.Mutation = (*SagaLogsMutation)(nil)

// sagalogsOption allows management of the mutation configuration using functional options.
type sagalogsOption func(*SagaLogsMutation)

// newSagaLogsMutation creates new mutation for the SagaLogs entity.
func newSagaLogsMutation(c config, op Op, opts ...sagalogsOption) *SagaLogsMutation {
	m := &SagaLogsMutation{
		config:        c,
		op:            op,
		typ:           TypeSagaLogs,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSagaLogsID sets the ID field of the mutation.
func withSagaLogsID(id int) sagalogsOption {
	return func(m *SagaLogsMutation) {
		var (
			err   error
			once  sync.Once
			value *SagaLogs
		)
		m.oldValue = func(ctx context.Context) (*SagaLogs, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().SagaLogs.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSagaLogs sets the old SagaLogs of the mutation.
func withSagaLogs(node *SagaLogs) sagalogsOption {
	return func(m *SagaLogsMutation) {
		m.oldValue = func(context.Context) (*SagaLogs, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SagaLogsMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SagaLogsMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of SagaLogs entities.
func (m *SagaLogsMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SagaLogsMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SagaLogsMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().SagaLogs.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetWorkflowID sets the "workflow_id" field.
func (m *SagaLogsMutation) SetWorkflowID(s string) {
	m.workflow_id = &s
}

// WorkflowID returns the value of the "workflow_id" field in the mutation.
func (m *SagaLogsMutation) WorkflowID() (r string, exists bool) {
	v := m.workflow_id
	if v == nil {
		return
	}
	return *v, true
}

// OldWorkflowID returns the old "workflow_id" field's value of the SagaLogs entity.
// If the SagaLogs object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SagaLogsMutation) OldWorkflowID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWorkflowID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWorkflowID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWorkflowID: %w", err)
	}
	return oldValue.WorkflowID, nil
}

// ResetWorkflowID resets all changes to the "workflow_id" field.
func (m *SagaLogsMutation) ResetWorkflowID() {
	m.workflow_id = nil
}

// SetWorkflowName sets the "workflow_name" field.
func (m *SagaLogsMutation) SetWorkflowName(s string) {
	m.workflow_name = &s
}

// WorkflowName returns the value of the "workflow_name" field in the mutation.
func (m *SagaLogsMutation) WorkflowName() (r string, exists bool) {
	v := m.workflow_name
	if v == nil {
		return
	}
	return *v, true
}

// OldWorkflowName returns the old "workflow_name" field's value of the SagaLogs entity.
// If the SagaLogs object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SagaLogsMutation) OldWorkflowName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWorkflowName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWorkflowName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWorkflowName: %w", err)
	}
	return oldValue.WorkflowName, nil
}

// ResetWorkflowName resets all changes to the "workflow_name" field.
func (m *SagaLogsMutation) ResetWorkflowName() {
	m.workflow_name = nil
}

// SetStepName sets the "step_name" field.
func (m *SagaLogsMutation) SetStepName(s string) {
	m.step_name = &s
}

// StepName returns the value of the "step_name" field in the mutation.
func (m *SagaLogsMutation) StepName() (r string, exists bool) {
	v := m.step_name
	if v == nil {
		return
	}
	return *v, true
}

// OldStepName returns the old "step_name" field's value of the SagaLogs entity.
// If the SagaLogs object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SagaLogsMutation) OldStepName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStepName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStepName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStepName: %w", err)
	}
	return oldValue.StepName, nil
}

// ResetStepName resets all changes to the "step_name" field.
func (m *SagaLogsMutation) ResetStepName() {
	m.step_name = nil
}

// SetUpdateAt sets the "update_at" field.
func (m *SagaLogsMutation) SetUpdateAt(t time.Time) {
	m.update_at = &t
}

// UpdateAt returns the value of the "update_at" field in the mutation.
func (m *SagaLogsMutation) UpdateAt() (r time.Time, exists bool) {
	v := m.update_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateAt returns the old "update_at" field's value of the SagaLogs entity.
// If the SagaLogs object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SagaLogsMutation) OldUpdateAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateAt: %w", err)
	}
	return oldValue.UpdateAt, nil
}

// ResetUpdateAt resets all changes to the "update_at" field.
func (m *SagaLogsMutation) ResetUpdateAt() {
	m.update_at = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *SagaLogsMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *SagaLogsMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the SagaLogs entity.
// If the SagaLogs object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SagaLogsMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *SagaLogsMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the SagaLogsMutation builder.
func (m *SagaLogsMutation) Where(ps ...predicate.SagaLogs) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SagaLogsMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SagaLogsMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.SagaLogs, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SagaLogsMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SagaLogsMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (SagaLogs).
func (m *SagaLogsMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SagaLogsMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.workflow_id != nil {
		fields = append(fields, sagalogs.FieldWorkflowID)
	}
	if m.workflow_name != nil {
		fields = append(fields, sagalogs.FieldWorkflowName)
	}
	if m.step_name != nil {
		fields = append(fields, sagalogs.FieldStepName)
	}
	if m.update_at != nil {
		fields = append(fields, sagalogs.FieldUpdateAt)
	}
	if m.created_at != nil {
		fields = append(fields, sagalogs.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SagaLogsMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case sagalogs.FieldWorkflowID:
		return m.WorkflowID()
	case sagalogs.FieldWorkflowName:
		return m.WorkflowName()
	case sagalogs.FieldStepName:
		return m.StepName()
	case sagalogs.FieldUpdateAt:
		return m.UpdateAt()
	case sagalogs.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SagaLogsMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case sagalogs.FieldWorkflowID:
		return m.OldWorkflowID(ctx)
	case sagalogs.FieldWorkflowName:
		return m.OldWorkflowName(ctx)
	case sagalogs.FieldStepName:
		return m.OldStepName(ctx)
	case sagalogs.FieldUpdateAt:
		return m.OldUpdateAt(ctx)
	case sagalogs.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown SagaLogs field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SagaLogsMutation) SetField(name string, value ent.Value) error {
	switch name {
	case sagalogs.FieldWorkflowID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWorkflowID(v)
		return nil
	case sagalogs.FieldWorkflowName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWorkflowName(v)
		return nil
	case sagalogs.FieldStepName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStepName(v)
		return nil
	case sagalogs.FieldUpdateAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateAt(v)
		return nil
	case sagalogs.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown SagaLogs field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SagaLogsMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SagaLogsMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SagaLogsMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown SagaLogs numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SagaLogsMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SagaLogsMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SagaLogsMutation) ClearField(name string) error {
	return fmt.Errorf("unknown SagaLogs nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SagaLogsMutation) ResetField(name string) error {
	switch name {
	case sagalogs.FieldWorkflowID:
		m.ResetWorkflowID()
		return nil
	case sagalogs.FieldWorkflowName:
		m.ResetWorkflowName()
		return nil
	case sagalogs.FieldStepName:
		m.ResetStepName()
		return nil
	case sagalogs.FieldUpdateAt:
		m.ResetUpdateAt()
		return nil
	case sagalogs.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown SagaLogs field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SagaLogsMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SagaLogsMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SagaLogsMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SagaLogsMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SagaLogsMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SagaLogsMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SagaLogsMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown SagaLogs unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SagaLogsMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown SagaLogs edge %s", name)
}
