// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ntc-goer/microservice-examples/registry/sagaorchestation/ent/predicate"
	"github.com/ntc-goer/microservice-examples/registry/sagaorchestation/ent/sagalogs"
)

// SagaLogsQuery is the builder for querying SagaLogs entities.
type SagaLogsQuery struct {
	config
	ctx        *QueryContext
	order      []sagalogs.OrderOption
	inters     []Interceptor
	predicates []predicate.SagaLogs
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SagaLogsQuery builder.
func (slq *SagaLogsQuery) Where(ps ...predicate.SagaLogs) *SagaLogsQuery {
	slq.predicates = append(slq.predicates, ps...)
	return slq
}

// Limit the number of records to be returned by this query.
func (slq *SagaLogsQuery) Limit(limit int) *SagaLogsQuery {
	slq.ctx.Limit = &limit
	return slq
}

// Offset to start from.
func (slq *SagaLogsQuery) Offset(offset int) *SagaLogsQuery {
	slq.ctx.Offset = &offset
	return slq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (slq *SagaLogsQuery) Unique(unique bool) *SagaLogsQuery {
	slq.ctx.Unique = &unique
	return slq
}

// Order specifies how the records should be ordered.
func (slq *SagaLogsQuery) Order(o ...sagalogs.OrderOption) *SagaLogsQuery {
	slq.order = append(slq.order, o...)
	return slq
}

// First returns the first SagaLogs entity from the query.
// Returns a *NotFoundError when no SagaLogs was found.
func (slq *SagaLogsQuery) First(ctx context.Context) (*SagaLogs, error) {
	nodes, err := slq.Limit(1).All(setContextOp(ctx, slq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sagalogs.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (slq *SagaLogsQuery) FirstX(ctx context.Context) *SagaLogs {
	node, err := slq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SagaLogs ID from the query.
// Returns a *NotFoundError when no SagaLogs ID was found.
func (slq *SagaLogsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = slq.Limit(1).IDs(setContextOp(ctx, slq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sagalogs.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (slq *SagaLogsQuery) FirstIDX(ctx context.Context) int {
	id, err := slq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SagaLogs entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SagaLogs entity is found.
// Returns a *NotFoundError when no SagaLogs entities are found.
func (slq *SagaLogsQuery) Only(ctx context.Context) (*SagaLogs, error) {
	nodes, err := slq.Limit(2).All(setContextOp(ctx, slq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sagalogs.Label}
	default:
		return nil, &NotSingularError{sagalogs.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (slq *SagaLogsQuery) OnlyX(ctx context.Context) *SagaLogs {
	node, err := slq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SagaLogs ID in the query.
// Returns a *NotSingularError when more than one SagaLogs ID is found.
// Returns a *NotFoundError when no entities are found.
func (slq *SagaLogsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = slq.Limit(2).IDs(setContextOp(ctx, slq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sagalogs.Label}
	default:
		err = &NotSingularError{sagalogs.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (slq *SagaLogsQuery) OnlyIDX(ctx context.Context) int {
	id, err := slq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SagaLogsSlice.
func (slq *SagaLogsQuery) All(ctx context.Context) ([]*SagaLogs, error) {
	ctx = setContextOp(ctx, slq.ctx, "All")
	if err := slq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SagaLogs, *SagaLogsQuery]()
	return withInterceptors[[]*SagaLogs](ctx, slq, qr, slq.inters)
}

// AllX is like All, but panics if an error occurs.
func (slq *SagaLogsQuery) AllX(ctx context.Context) []*SagaLogs {
	nodes, err := slq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SagaLogs IDs.
func (slq *SagaLogsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if slq.ctx.Unique == nil && slq.path != nil {
		slq.Unique(true)
	}
	ctx = setContextOp(ctx, slq.ctx, "IDs")
	if err = slq.Select(sagalogs.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (slq *SagaLogsQuery) IDsX(ctx context.Context) []int {
	ids, err := slq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (slq *SagaLogsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, slq.ctx, "Count")
	if err := slq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, slq, querierCount[*SagaLogsQuery](), slq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (slq *SagaLogsQuery) CountX(ctx context.Context) int {
	count, err := slq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (slq *SagaLogsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, slq.ctx, "Exist")
	switch _, err := slq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (slq *SagaLogsQuery) ExistX(ctx context.Context) bool {
	exist, err := slq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SagaLogsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (slq *SagaLogsQuery) Clone() *SagaLogsQuery {
	if slq == nil {
		return nil
	}
	return &SagaLogsQuery{
		config:     slq.config,
		ctx:        slq.ctx.Clone(),
		order:      append([]sagalogs.OrderOption{}, slq.order...),
		inters:     append([]Interceptor{}, slq.inters...),
		predicates: append([]predicate.SagaLogs{}, slq.predicates...),
		// clone intermediate query.
		sql:  slq.sql.Clone(),
		path: slq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		WorkflowID string `json:"workflow_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SagaLogs.Query().
//		GroupBy(sagalogs.FieldWorkflowID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (slq *SagaLogsQuery) GroupBy(field string, fields ...string) *SagaLogsGroupBy {
	slq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SagaLogsGroupBy{build: slq}
	grbuild.flds = &slq.ctx.Fields
	grbuild.label = sagalogs.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		WorkflowID string `json:"workflow_id,omitempty"`
//	}
//
//	client.SagaLogs.Query().
//		Select(sagalogs.FieldWorkflowID).
//		Scan(ctx, &v)
func (slq *SagaLogsQuery) Select(fields ...string) *SagaLogsSelect {
	slq.ctx.Fields = append(slq.ctx.Fields, fields...)
	sbuild := &SagaLogsSelect{SagaLogsQuery: slq}
	sbuild.label = sagalogs.Label
	sbuild.flds, sbuild.scan = &slq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SagaLogsSelect configured with the given aggregations.
func (slq *SagaLogsQuery) Aggregate(fns ...AggregateFunc) *SagaLogsSelect {
	return slq.Select().Aggregate(fns...)
}

func (slq *SagaLogsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range slq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, slq); err != nil {
				return err
			}
		}
	}
	for _, f := range slq.ctx.Fields {
		if !sagalogs.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if slq.path != nil {
		prev, err := slq.path(ctx)
		if err != nil {
			return err
		}
		slq.sql = prev
	}
	return nil
}

func (slq *SagaLogsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SagaLogs, error) {
	var (
		nodes = []*SagaLogs{}
		_spec = slq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SagaLogs).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SagaLogs{config: slq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, slq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (slq *SagaLogsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := slq.querySpec()
	_spec.Node.Columns = slq.ctx.Fields
	if len(slq.ctx.Fields) > 0 {
		_spec.Unique = slq.ctx.Unique != nil && *slq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, slq.driver, _spec)
}

func (slq *SagaLogsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sagalogs.Table, sagalogs.Columns, sqlgraph.NewFieldSpec(sagalogs.FieldID, field.TypeInt))
	_spec.From = slq.sql
	if unique := slq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if slq.path != nil {
		_spec.Unique = true
	}
	if fields := slq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sagalogs.FieldID)
		for i := range fields {
			if fields[i] != sagalogs.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := slq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := slq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := slq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := slq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (slq *SagaLogsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(slq.driver.Dialect())
	t1 := builder.Table(sagalogs.Table)
	columns := slq.ctx.Fields
	if len(columns) == 0 {
		columns = sagalogs.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if slq.sql != nil {
		selector = slq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if slq.ctx.Unique != nil && *slq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range slq.predicates {
		p(selector)
	}
	for _, p := range slq.order {
		p(selector)
	}
	if offset := slq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := slq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SagaLogsGroupBy is the group-by builder for SagaLogs entities.
type SagaLogsGroupBy struct {
	selector
	build *SagaLogsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (slgb *SagaLogsGroupBy) Aggregate(fns ...AggregateFunc) *SagaLogsGroupBy {
	slgb.fns = append(slgb.fns, fns...)
	return slgb
}

// Scan applies the selector query and scans the result into the given value.
func (slgb *SagaLogsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, slgb.build.ctx, "GroupBy")
	if err := slgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SagaLogsQuery, *SagaLogsGroupBy](ctx, slgb.build, slgb, slgb.build.inters, v)
}

func (slgb *SagaLogsGroupBy) sqlScan(ctx context.Context, root *SagaLogsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(slgb.fns))
	for _, fn := range slgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*slgb.flds)+len(slgb.fns))
		for _, f := range *slgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*slgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := slgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SagaLogsSelect is the builder for selecting fields of SagaLogs entities.
type SagaLogsSelect struct {
	*SagaLogsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sls *SagaLogsSelect) Aggregate(fns ...AggregateFunc) *SagaLogsSelect {
	sls.fns = append(sls.fns, fns...)
	return sls
}

// Scan applies the selector query and scans the result into the given value.
func (sls *SagaLogsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sls.ctx, "Select")
	if err := sls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SagaLogsQuery, *SagaLogsSelect](ctx, sls.SagaLogsQuery, sls, sls.inters, v)
}

func (sls *SagaLogsSelect) sqlScan(ctx context.Context, root *SagaLogsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sls.fns))
	for _, fn := range sls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
