// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/ntc-goer/microservice-examples/kitchen/ent/schema"
	"github.com/ntc-goer/microservice-examples/kitchen/ent/ticket"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	ticketFields := schema.Ticket{}.Fields()
	_ = ticketFields
	// ticketDescOrderID is the schema descriptor for order_id field.
	ticketDescOrderID := ticketFields[1].Descriptor()
	// ticket.OrderIDValidator is a validator for the "order_id" field. It is called by the builders before save.
	ticket.OrderIDValidator = ticketDescOrderID.Validators[0].(func(string) error)
	// ticketDescRequestID is the schema descriptor for request_id field.
	ticketDescRequestID := ticketFields[2].Descriptor()
	// ticket.RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	ticket.RequestIDValidator = ticketDescRequestID.Validators[0].(func(string) error)
	// ticketDescUpdateAt is the schema descriptor for update_at field.
	ticketDescUpdateAt := ticketFields[4].Descriptor()
	// ticket.DefaultUpdateAt holds the default value on creation for the update_at field.
	ticket.DefaultUpdateAt = ticketDescUpdateAt.Default.(func() time.Time)
	// ticketDescCreatedAt is the schema descriptor for created_at field.
	ticketDescCreatedAt := ticketFields[5].Descriptor()
	// ticket.DefaultCreatedAt holds the default value on creation for the created_at field.
	ticket.DefaultCreatedAt = ticketDescCreatedAt.Default.(func() time.Time)
	// ticketDescID is the schema descriptor for id field.
	ticketDescID := ticketFields[0].Descriptor()
	// ticket.DefaultID holds the default value on creation for the id field.
	ticket.DefaultID = ticketDescID.Default.(func() uuid.UUID)
}
