// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TicketsColumns holds the columns for the "tickets" table.
	TicketsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "order_id", Type: field.TypeString},
		{Name: "request_id", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"CREATE_PENDING", "AWAITING_ACCEPTANCE", "CANCELED"}},
		{Name: "update_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// TicketsTable holds the schema information for the "tickets" table.
	TicketsTable = &schema.Table{
		Name:       "tickets",
		Columns:    TicketsColumns,
		PrimaryKey: []*schema.Column{TicketsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TicketsTable,
	}
)

func init() {
	TicketsTable.Annotation = &entsql.Annotation{
		Table: "tickets",
	}
}
