grpc_port: 50005

queue:
  subjects:
    create_order_subject: CREATE_ORDER
    test_subject: TEST

services:
  # Service Name
  lb_service_host: "localhost:9999"
  order_service_name: order
  consumer_service_name: consumer
  orchestrator_service_name: orchestrator
