service_port: 50005

# Broker
broker:
  address: localhost:4222
  subject:
    create_order: CREATE_ORDER_SUBJECT
    test_subject: TEST_SUBJECT
    send_mail: SEND_MAIL_SUBJECT
  queue:
    orchestrator: ORCHESTRATOR_QUEUE
    mail: MAIL_QUEUE

# Service Name
service:
  lb_service_host: localhost:9999
  order_service_name: order
  consumer_service_name: consumer
  orchestrator_service_name: orchestrator
  mail_service_name: mail