// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ntc-goer/microservice-examples/orchestrator/config"
	"github.com/ntc-goer/microservice-examples/orchestrator/service"
	"github.com/ntc-goer/microservice-examples/registry/broker"
	"github.com/ntc-goer/microservice-examples/registry/serviceregistration/common"
	"github.com/ntc-goer/microservice-examples/registry/serviceregistration/consul"
)

// Injectors from wire.go:

//go:generate wire
func InitializeDependency(dcType string) (*CoreDependency, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	brokerBroker := broker.NewBroker()
	healthService, err := service.NewHealthService()
	if err != nil {
		return nil, err
	}
	createOrderService := service.NewCreateOrderService(configConfig)
	coreService := service.NewCoreService(brokerBroker, healthService, createOrderService, configConfig)
	registry, err := consul.NewRegistry()
	if err != nil {
		return nil, err
	}
	coreDependency := NewCoreDependency(configConfig, coreService, registry, brokerBroker)
	return coreDependency, nil
}

// wire.go:

type CoreDependency struct {
	Config           *config.Config
	CoreService      *service.CoreService
	ServiceDiscovery common.DiscoveryI
	Broker           *broker.Broker
}

func NewCoreDependency(cfg *config.Config, coreSrv *service.CoreService, srvDis common.DiscoveryI, br *broker.Broker) *CoreDependency {
	return &CoreDependency{
		Config:           cfg,
		ServiceDiscovery: srvDis,
		CoreService:      coreSrv,
		Broker:           br,
	}
}
