// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ntc-goer/microservice-examples/orchestrator/config"
	"github.com/ntc-goer/microservice-examples/orchestrator/pkg"
	"github.com/ntc-goer/microservice-examples/orchestrator/service"
	"github.com/ntc-goer/microservice-examples/registry/broker"
	"github.com/ntc-goer/microservice-examples/registry/serviceregistration/common"
	"github.com/ntc-goer/microservice-examples/registry/serviceregistration/consul"
)

// Injectors from wire.go:

//go:generate wire
func InitializeDependency(dcType string) (*CoreDependency, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	lb := pkg.NewLB(configConfig)
	brokerBroker := broker.NewBroker()
	impl, err := service.NewServiceImpl(configConfig, lb, brokerBroker)
	if err != nil {
		return nil, err
	}
	registry, err := consul.NewRegistry()
	if err != nil {
		return nil, err
	}
	coreDependency := NewCoreDependency(configConfig, impl, registry)
	return coreDependency, nil
}

// wire.go:

type CoreDependency struct {
	Config           *config.Config
	ServiceImpl      *service.Impl
	ServiceDiscovery common.DiscoveryI
}

func NewCoreDependency(cfg *config.Config, srvImpl *service.Impl, srvDis common.DiscoveryI) *CoreDependency {
	return &CoreDependency{
		Config:           cfg,
		ServiceImpl:      srvImpl,
		ServiceDiscovery: srvDis,
	}
}
