// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ntc-goer/microservice-examples/orderservice/config"
	"github.com/ntc-goer/microservice-examples/orderservice/repository"
	"github.com/ntc-goer/microservice-examples/orderservice/service"
	"github.com/ntc-goer/microservice-examples/registry/broker"
	"github.com/ntc-goer/microservice-examples/registry/serviceregistration/common"
	"github.com/ntc-goer/microservice-examples/registry/serviceregistration/consul"
)

// Injectors from wire.go:

//go:generate wire
func InitializeDependency(dcType string) (*CoreDependency, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	healthService, err := service.NewHealthService()
	if err != nil {
		return nil, err
	}
	repositoryRepository, err := repository.NewRepository(configConfig)
	if err != nil {
		return nil, err
	}
	brokerBroker := broker.NewBroker()
	orderService := service.NewOrderService(repositoryRepository, configConfig, brokerBroker)
	dishService := service.NewDishService(repositoryRepository)
	coreService := service.NewCoreService(healthService, orderService, dishService)
	registry, err := consul.NewRegistry()
	if err != nil {
		return nil, err
	}
	coreDependency := NewCoreDependency(configConfig, coreService, registry, repositoryRepository, brokerBroker)
	return coreDependency, nil
}

// wire.go:

type CoreDependency struct {
	Config           *config.Config
	CoreService      *service.CoreService
	ServiceDiscovery common.DiscoveryI
	Repository       *repository.Repository
	Broker           *broker.Broker
}

func NewCoreDependency(cfg *config.Config, coreSrv *service.CoreService, srvDis common.DiscoveryI, r *repository.Repository, br *broker.Broker) *CoreDependency {
	return &CoreDependency{
		Config:           cfg,
		CoreService:      coreSrv,
		ServiceDiscovery: srvDis,
		Repository:       r,
		Broker:           br,
	}
}
