// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DishesColumns holds the columns for the "dishes" table.
	DishesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "order_id", Type: field.TypeUUID},
		{Name: "dish_id", Type: field.TypeString},
		{Name: "dish_name", Type: field.TypeString},
		{Name: "quantity", Type: field.TypeInt},
		{Name: "update_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// DishesTable holds the schema information for the "dishes" table.
	DishesTable = &schema.Table{
		Name:       "dishes",
		Columns:    DishesColumns,
		PrimaryKey: []*schema.Column{DishesColumns[0]},
	}
	// OrdersColumns holds the columns for the "orders" table.
	OrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "request_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeString},
		{Name: "address", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"APPROVAL_PENDING", "APPROVED", "FAILED"}},
		{Name: "update_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// OrdersTable holds the schema information for the "orders" table.
	OrdersTable = &schema.Table{
		Name:       "orders",
		Columns:    OrdersColumns,
		PrimaryKey: []*schema.Column{OrdersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DishesTable,
		OrdersTable,
	}
)

func init() {
	DishesTable.Annotation = &entsql.Annotation{
		Table: "dishes",
	}
	OrdersTable.Annotation = &entsql.Annotation{
		Table: "orders",
	}
}
